### ISSUE TITLE
AoC terms of service disallow submitting to AI same-day

### ISSUE THREAD

**Issue by shannonmoeller** [heiko-hotz/advent-of-code-2024-gemini#2]
> **Can I use AI to get on the global leaderboard?** Please don't use AI / [LLMs](https://en.wikipedia.org/wiki/Large_language_model) (like GPT) to automatically solve a day's puzzles until that day's global leaderboards are full. By "automatically", I mean using AI to do most or all of the puzzle solving, like handing the puzzle text directly to an LLM. The leaderboards are for human competitors; if you want to compare the speed of your AI solver with others, please do so elsewhere. (If you want to use AI to help you solve puzzles, I can't really stop you, but I feel like it's harder to get better at programming if you ask an AI to do the programming for you.)

https://adventofcode.com/2024/about

**Comment by heiko-hotz** [comment]
Acknowledged 👍 That being said the TOS only asks to wait until the leaderboard is full (which is usually within 5 minutes)
